server:
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tuna_db
    username: root
    password: mariadb
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql 